runtime: python27
api_version: 1
threadsafe: true

#with help from https://gist.github.com/darktable/873098
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: oauth.app

libraries:
- name: endpoints
  version: 1.0
